apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka

spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 2
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          name: internal
        volumeMounts:
        - name: data-kafka
          mountPath: /kafka
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-client:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: BROKER_ID
          value: "1"

  volumeClaimTemplates:
  - metadata:
      name: data-kafka
      labels:
        app: kafka
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi