apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi

  replicas: 1
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: apache/nifi:latest
          ports:
            - name: http
              containerPort: 8180
          env:
          - name: NIFI_WEB_HTTP_PORT
            value: "8180"

          volumeMounts:
           - name: nifi-data
             mountPath: /opt/nifi/nifi-1.15.3/conf
             subPath: conf
             
      volumes: 
        - name: nifi-data
          persistentVolumeClaim: 
            claimName: nifi-pvc